### ISSUE TITLE
mssql db admin secret doesn't get created in SRE deployment

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1318]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** Mac
- **Data Safe Haven version:** Develop (4.0.0)

## :no_entry_sign: Describe the problem

`./Setup_SRE_Databases.ps1` for my SRE deployment threw an error because it couldn't find the correct secret:

```
2022-10-13 13:58:47 [   INFO]: Creating/retrieving secrets from Key Vault 'kv-blue-sre-edt2ms'...
2022-10-13 13:58:47 [FAILURE]: [x] Secret 'sre-edt2ms-db-admin-username-mssql does not exist and no default value or length was provided!
Exception: Secret 'sre-edt2ms-db-admin-username-mssql does not exist and no default value or length was provided!
```

### SRE config

```
{
    "sreId": "edt2ms",
    "tier": "2",
    "shmId": "blue",
    "subscriptionName": "Data Safe Haven Development",
    "ipPrefix": "10.11.16",
    "inboundAccessFrom": ["193.60.220.253"],
    "outboundInternetAccess": "default",
    "computeVmImage": {
        "type": "Ubuntu",
        "version": "20.04.2022081900"
    },
    "remoteDesktopProvider": "MicrosoftRDS",
    "dataAdminIpAddresses": ["193.60.220.253"],
    "databases": ["MSSQL", "PostgreSQL"]
}
```

## TODO:

This could be because I initially didn't include the "databases" field in the config above (only realising it was mandatory and updating this at some point during deployment), so it's possible an earlier step of the deployment that should have set up the secret didn't - I'll need to investigate.

**Comment by jemrobinson** [comment]
Yes, this secret should be created when `Setup_SRE_Key_Vault_And_Users.ps1` is run.

**Comment by edwardchalstrey1** [comment]
> Yes, this secret should be created when `Setup_SRE_Key_Vault_And_Users.ps1` is run.

@jemrobinson ok thanks, I'll close this then as not a real issue
