### ISSUE TITLE
Password expiration can prevent Ubuntu VM log-in

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#1443]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **using** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Data Safe Haven version:** 4.0.3/develop
- **Browser details:** Chrome
- **Operating system details:** MacOS

## :no_entry_sign: Describe the problem

On a newly deployed T3 TRE, I couldn't log in to the Ubuntu SRD, despite being able to reach Guacamole with no difficulty. The Ubuntu VM requires a change of password due to its being expired - the user account has been on the SHM for quite some time, so may be to do with that? This is not clear when logging in using the Desktop GUI as no relevant warning message is displayed - 

<img width="419" alt="image" src="https://user-images.githubusercontent.com/5796417/232519065-ebcd0ebd-9296-4ed6-a0bf-1b8c4093c90b.png">

It only becomes clear when logging in to the VM using SSH. The password expiration date policy must be mismatched somewhere.

<img width="504" alt="Screenshot 2023-04-17 at 15 29 53" src="https://user-images.githubusercontent.com/5796417/232517437-2fbdbedc-9f31-4c57-88e0-0516fcf43387.png">

## :steam_locomotive: Workarounds or solutions

The user should be able to fix it for themselves by resetting their password, presumably using the "Forgot my password" routine when initially logging in. 

We may need to add some additional documentation to more explicitly cover this issue, although the existing documentation would probably end up with users resetting their account, and thus solving their problem anyway.

## TODO

- [x] #1465

**Comment by JimMadge** [comment]
Can you check AD for any information like,

- whether that password has expired
- are there password expiration rules

Can you also connect using the administrator account and use [`chage`](https://man7.org/linux/man-pages/man1/chage.1.html) to check for the system password (which should be unset) expiry?

It would be good to find out whether this is the AD password or system password.

**Comment by JimMadge** [comment]
As expected, no local user or password

```console
$ chage -l $USER
chage: user ... does not exist in /etc/passwd
```

**Comment by JimMadge** [comment]
For an actual local user, no password expiry

```console
sresatret1admin:~$ chage -l $USER
Last password change                                    : May 04, 2023
Password expires                                        : never
Password inactive                                       : never
Account expires                                         : never
Minimum number of days between password change          : 0
Maximum number of days between password change          : 99999
Number of days of warning before password expires       : 7
```

**Comment by JimMadge** [comment]
And confirmed that AAD users do not have an entry in `/etc/shadow`.

**Comment by craddm** [comment]
So, I just logged on to the DC in the SHM. For the users on there, "password never expires" is unticked by default. I ticked it for the account I had this issue on, and now I can log into the VM. So it's the AD that's the issue

**Comment by JimMadge** [comment]
Great, so I think we need to answer

1. Do we say that passwords will expire?
2. Do we think that they should?

Then we can either check it is properly documented or look at how to check "password never expires" automatically (or add that as a manual step if we need to).

**Comment by craddm** [comment]
Can't see it anywhere in the docs. 

I can see an argument for letting them expire as a sort of entropic way of rescinding access, but it does feel a bit awkward when telling the user what the problem is isn't obvious. And it feels mismatched with the security policy of the AAD tenant, where the passwords don't expire, so slightly leaning towards setting them to never expire on the local AD either.

**Comment by jemrobinson** [comment]
I agree that password expiry isn't a good solution to removing users, and since they can reset their passwords anyway it doesn't even achieve this! We create users on the SHM using a Powershell script. It should be easy to modify this to add the "password never expires" property (which we already do for admin accounts anyway). Anyone want to volunteer to do this?

**Comment by edwardchalstrey1** [comment]
- [ ] Update bad password tip to login tip to include password expiry
