### ISSUE TITLE
Pulumi: replace domain controller with AzureAD proxy

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1570]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

We should write a proxy server that can accept LDAP requests and query AzureAD for the answers. Ideally this should be available as a Docker image.

## :steam_locomotive: How could this be done?

~The Python [ldaptor](https://ldaptor.readthedocs.io) package might be a good place to start.~
I've got a proof-of-concept working [here](https://github.com/alan-turing-institute/apricot) which I've called Apricot.

- [x] Add required AzureAD/GraphAPI functionality to the code (see #1778)
- [x] Update SRE components to use Apricot for authentication/identity (see #1772)
- [x] Remove the SHM domain controller (see #1805)
