### ISSUE TITLE
Using Let's Encrypt SSL certificates with Feb 2018 runbook

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/data-safe-haven#187]
## Summary
Issue generated while validating the Feb 2018 DSG Azure deployment runbook (see PR #174).

The Feb 2018 runbook has the following process to get a CA-signed SSL cert on the RDS Gateway Server (VM name = RDS):
- Generate CSR
- Get CSR signed by CA
- Import signed CSR to IIS

For test environments we don't want to necessarily pay for an SSL certificate, but we want to generate each new test environment from scratch.

Close this issue when the DSG side of this information is included in the Feb 2018 runbook as amended by PR #174.

#### Testing
- [x] Create a security group called `Safe Haven Management Test Admins` (see issue #188 for details)
- Give this group access to the following resources
  - [x] `Safe Haven Management Test` Azure subscription (done in issue #188)
  - [x] `dsg-management-test` KeyVault secret access (by adding to Access Policies).
  - [x] The `dsgroupdev.co.uk` DNS Zone (move to `Safe Haven Management Test` subscription - done in issue #188)
  - [x] For the runbook validation, the `dsgroup9.co.uk` DNS Zone (we will stop using these separate domains in future) (move to `Safe Haven Management Test` subscription - done in issue #188)
#### Production
- [x] Create a security group called `Safe Haven Management Production Admins` (see issue #188 for details)
- Give this group access to the following resources
  - [x] `Safe Haven Management` Azure subscription
  - [ ] `dsg-management-prod` KeyVault secret access (by adding to Access Policies)
  - [x] The `turingsafehaven.ac.uk` DNS service (move to `Safe Haven Management` subscription)
  - [ ] The `dsgroup1.co.uk` DNS service (move to `Safe Haven Management` subscription)
  - [ ] The `dsgroup2.co.uk` DNS service (move to `Safe Haven Management` subscription)
  - [ ] The `dsgroup3.co.uk` DNS service (move to `Safe Haven Management` subscription)
  - [ ] The `dsgroup4.co.uk` DNS service (move to `Safe Haven Management` subscription)
  - [ ] The `dsgroup5.co.uk` DNS service (move to `Safe Haven Management` subscription)
  - [ ] The `dsgroup6.co.uk` DNS service (move to `Safe Haven Management` subscription)
  - [ ] The `dsgroup7.co.uk` DNS service (move to `Safe Haven Management` subscription)
  - [ ] The `dsgroup8.co.uk` DNS service (move to `Safe Haven Management` subscription)

#### DSG DNS Zone setup
- When creating a secure project environment, create a DNS Zone for `<project-id>.<management-domain>` (e.g. `dsg9.dsgroupdev.co.uk` or `dsg-april19-roche.turingsafehaven.ac.uk`)
- In the DNS Zone for the management domain, add NS records for the <project-id> subdomain as shown in the subdomain's DNS Zone

### Let's Encrypt SSL certificate generation and installation
- On the DSG RDS server create a certificate request as per the runbook
- Copy the CSR from the RDS server to your computer
- [Install Certbot](https://certbot.eff.org/) on your computer if required
- Run Certbot, passing in custom folders for config, work and logs directories. This will automatically create a new Let's Encrypt account for this particular pairing of Certbot installation and custom directory.
  - `certbot --config-dir ~/tsh-certbot/config --work-dir ~/tsh-certbot/work --logs-dir ~/tsh-certbot/logs certonly --manual --preferred-challenges "dns" --agree-tos -m <email-for-expiry-notifications> -d <dsg-domain> --csr <path-to-csr>`
- When presented with the DNS challenge from Certbot, add a record to the DNS Zone for the DSG domain with the following properties
  - **Name:** First section of the name provided by Certbot (e.g. `_acme-challenge`)
  - **Type:** TXT
  - **TTL:** 30 seconds
  - **Value:** The value provided by Certbot (a long random looking string)
- Wait for Let's Encrypt to verify the challenge
- Copy `~/tsh-certbot/config/live/<dsg-fq-domain>/fullchain.pem` from your computer to the RDS server
- On the DSG RDS Server, complete the certificate request as per the runbook
- Securely delete the  `~/tsh-certbot` directory. Note that, when using a CSR, neither the CSR nor the signed certificate files are sensitive. However, the private key in the `accounts` subfolder is now authorised to create new certs for the DSG domain, which is sensitive.
- Delete the DNS TEXT record you created earlier for the Let's Encrypt challenge. This will ensure that the private key in the folder you just deleted will not be able to issue new Let's Encrypt certificates for the DSG domain once Let's Encrpt'd cached authorisation expired (currently Let's Encrypt cache authorisations for 30 days).
