### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1922]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

We should ensure that our logging is improved by:

- logging more things
- alerting when things are not as expected

## :steam_locomotive: How could this be done?

Could consolidate in LogAnalyticsWorkspace and send to e.g. GreyLog? Not sure on the best way to alert

## Task list

- [x] #1931 
- [x] #2295
- [x] #2307
- [x] #2309
- [x] #2318

**Comment by JimMadge** [comment]
Related to #1931

**Comment by JimMadge** [comment]
[Azure monitor data source](https://learn.microsoft.com/en-us/azure/azure-monitor/data-sources)

Log sources are:

- Azure resources (most azure resources, I think this is basic data like SKU, state, ...)
- Entra ID (audit data, authentication events _etc._)
- App insights (data from app services like webapps)
- Virtual machines (_e.g._ syslog)
- Kubernetes Clusters
- Custom sources, using the REST API

I think our working assumption was that using the Azure logging resources would mean we are easily able to ingest logs from Azure resources, whereas using an alternative log manager would involve lots of work to ingest logs.

The number of things which Azure monitor can ingest natively is fairly limited though so there might not be such a big advantage to using it.

**Comment by craddm** [comment]
Additional logs to investigate:

- Network events
  - Firewall logs
  - NSG logs
- Service logs
  - Containers
    - apricot
    - guac user sync
    - Nexus allowlist
    - Gitea
    - Hedgedoc
- Event logs
  - Data ingress
  - Data egress
- Authentication logs
  - From VM (PAM, ldap)
  - Entra (would need to work cross tenant)

**Comment by craddm** [comment]
Logging from container instances https://learn.microsoft.com/en-us/azure/container-instances/monitor-azure-container-instances

> Log Analytics workspaces provide a centralized location for storing and querying log data not only from Azure resources, but also on-premises resources and resources in other clouds. Azure Container Instances includes built-in support for sending logs and event data to Azure Monitor logs.
>
> To send container group log and event data to Azure Monitor logs, specify an existing Log Analytics workspace ID and workspace key when configuring a container group.

Seems like this _must_ be configured when deploying a container group.

In `pulumi-azure-native` https://www.pulumi.com/registry/packages/azure-native/api-docs/containerinstance/containergroup/#loganalytics

**Comment by craddm** [comment]
- Can't enable LogAnalytics/Diagnostic settings directly on the Entra tenants we use, since these features require a subscription on the tenant
- Simplest solution probably just to direct people to the right place, rather than try to find a way to ingest these logs into a central Log Analytics Workspace
- Logs available on Entra
  - User sign-in
  - Audit
  - Provisioning

**Comment by JimMadge** [comment]
[firewall monitoring](https://learn.microsoft.com/en-us/azure/firewall/firewall-workbook)

**Comment by craddm** [comment]
One complexity is that network flow logs require a Network Watcher. 
There is only one network watcher per region per subscription, which by default gets automatically created when any virtual network gets created within the subscription.

https://learn.microsoft.com/en-us/azure/network-watcher/network-watcher-overview

This means we need to import the existing network watcher resource rather than create it and manage it ourselves (and assume, if there is not one already, that it'll be created during our deployment). May be an issue if users have already created their own network watcher with a non-default name etc

**Comment by jemrobinson** [comment]
It's fine to postpone network flow logs for a future release if it's not a quick fix. Better to have *some* things working (and know which ones need to be added later) than have nothing ready until it all is.

**Comment by JimMadge** [comment]
Looks like there isn't anything useful we can get out of the virtual networks/NSGs.

Metrics are not supported by log analytics, and @craddm noted an issue with the flow logs (not actually sure what those are).

**Comment by jemrobinson** [comment]
Looks like [virtual network flow logs](https://learn.microsoft.com/en-us/azure/network-watcher/vnet-flow-logs-overview) are the new thing (NSG flow logs deprecated from 2027). Not sure if they are any easier to use though.

**Comment by JimMadge** [comment]
It seems like most 'Azure native' resources collect logs and metrics, which you can collect in a log analytics workspace using a [Diagnostic setting](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings) ([in pulumi](https://www.pulumi.com/registry/packages/azure-native/api-docs/insights/diagnosticsetting/)).

**Comment by craddm** [comment]
> Looks like [virtual network flow logs](https://learn.microsoft.com/en-us/azure/network-watcher/vnet-flow-logs-overview) are the new thing (NSG flow logs deprecated from 2027). Not sure if they are any easier to use though.

Also won't be able to create new NSG flow logs from [June 30 2025](https://learn.microsoft.com/en-us/azure/network-watcher/nsg-flow-logs-overview)

Assume the pulumi flow logs are virtual network flow logs rather than NSG flow logs, but it's not explicitly stated https://www.pulumi.com/registry/packages/azure-native/api-docs/network/flowlog/

**Comment by craddm** [comment]
> Looks like there isn't anything useful we can get out of the virtual networks/NSGs.
> 
> Metrics are not supported by log analytics, and @craddm noted an issue with the flow logs (not actually sure what those are).

flow logs should keep track of things like network traffic (source and destinations) and how the NSG rules are being applied

**Comment by JimMadge** [comment]
> flow logs should keep track of things like network traffic (source and destinations) and how the NSG rules are being applied

I think that is what we would want. But it sounds difficult because it has to use the subscription wide network watcher?

If so, I think it would be OK to leave it for now.

**Comment by craddm** [comment]
> > flow logs should keep track of things like network traffic (source and destinations) and how the NSG rules are being applied
> 
> I think that is what we would want. But it sounds difficult because it has to use the subscription wide network watcher?
> 
> If so, I think it would be OK to leave it for now.

Yes, I'm not sure if there's a way to get Pulumi to import it if it exists or create it if it doesn't - I think it's a problem like this [Pulumi issue](https://github.com/pulumi/pulumi/issues/3388)
