### ISSUE TITLE
Update Tier 3 Security evaluation checklist

### ISSUE THREAD

**Issue by helen-d-little** [alan-turing-institute/data-safe-haven#2285]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?
In the documentation for v 5.0.1 [Security checklist for T3 SREs](https://data-safe-haven.readthedocs.io/en/v5.0.1/deployment/security_checklist.html#physical-security-policy-tier-3) the physical security checks are inconsistent. If the user is connecting from the correct IP address via a VPN then the SHM will not disallow the connection. 

Also in the documentation:
>Verify that: check the network IP ranges corresponding to the research spaces and compare against the IPs accepted by the firewall.

But it is the NSGs which allow/disallow IPs?

## :memo: Required documentation changes
Remove the statement 
>Connection from outside the secure physical space is not possible.

**Comment by jemrobinson** [comment]
@helendduncan - the recommendation for tier 3 is to set up a network that can *only* be accessed from a known physical space (i.e. not via a VPN).
