### ISSUE TITLE
[DISCUSSION]: Reduce cost of running SHM and SRE environments

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/data-safe-haven#317]
We're currently paying thousands of dollars per month to keep the SHM and SRE environments running. For DSG SREs, the data prep and report writing phases can last a month before and 2-3 months after. For the Warwick Data Science for Social Good (DSSG) programme we need to run an SHM and up to 6 SREs for at least 3 months.

## SRE costs
| Component | Cost (UK South) |
|---|---|
| VPN Gateway | ~$138.70/month (VpnGw1) |
| AD Domain Controller | ~$74.46/month (B2ms) / ~$151.84/month (D2s v3) |
| RDS Gateway | ~$74.46/month (B2ms) / ~$151.84/month (D2s v3) |
| RDS App server | ~$74.46/month (B2ms) / ~$151.84/month (D2s v3) |
| RDS Presentation server | ~$74.46/month (B2ms) / ~$151.84/month (D2s v3) |
| Data server | ~$74.46/month (B2ms) / ~$151.84/month (D2s v3) |
| Hack MD server | ~$68.9120/month (B2ms) / ~$84.68/month (D2s v3) |
| Gitlab server | ~$68.9120/month (B2ms) / ~$84.68/month (D2s v3) |
| Compute VM | ~$84.68/month (D2s v3) / ~$338.72/month (D8s v3) |

## Candidate "quick fixes" for cost savings
- [x] Make AD + RDS + Data + HackMD + Gitlab servers size B2ms
- [x] Remove the DSG AD domain controllers (see issue #515)
- [ ] Combine the SHM DC + NPS (see issue #534)
- [x] Add LaTeX and slide software to compute VM to remove the need for the Windows virtual desktop Session Host and remove this Session Host
    - [x] Texlive LaTeX package added in Pr #348 
    - [x] Libre Office will be added via issue #371 
    - [x] Remove virtual desktop session host from RDS deployment template / scripts / instructions
- [ ] Combine Github + HackMD servers onto one VM
- [ ] Combine RemoteApp Session Host and Gateway VMs into a single VM per DSG.
  - [ ] Check if the size needed for performance is more or less expensive that the size needed for two separate VMs.   - [ ]   
  - [ ] Do some baseline load testing of the current config first at various VM sizes. If we can consolidate the RDS Gateway and RemoteApp Session Host to a single VM of the same size as the Session Host requires on its own, then there's no cost saving centralising the RDS Gateway to the management segment (or presumably moving to the Windows Virtual Desktop Azure service), though there may be management / deployment effort savings by centralising this (and we'd save a few ££ on domains).

## More structural changes to consider
- [ ] Replace AD DC VM with [Azure Active Directory Domain Services](https://docs.microsoft.com/en-us/azure/active-directory-domain-services/overview) (see issue #540)
- [ ] Replace per-DSG RDS Gateway VMs with single central RDS Gateway box, linking to per-SRE RemoteApp Session Host VMs and using the folder property of the RemoteApp config to group the apps by DSG for display. **NOTE:** This would likely prevent us having per-DSG inbound firewall rules for connection to the RDS Gateway service so would change our perimeter security model.
- [ ] Replace centralised RDS Gateway with the Azure hosted [Microsoft Virtual Desktop](https://docs.microsoft.com/en-us/azure/virtual-desktop/overview). We can test this while it's in preview but we should hold off from production deployment until it is generally available. For example, the management plane is only available in East US currently. **NOTE:** This would likely prevent us having per-DSG inbound firewall rules for connection to the RDS Gateway service so would change our perimeter security model. See issue #541.
