### ISSUE TITLE
Bristol DSG Network preparations

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/data-safe-haven#386]
## Info
- 6 groups (which Tiers? - should know after meeting on 2nd July)
  - Initial classification all Tier 0/1, but one queried whether it is personally linked data (we'll find out by 10th).
- Applications close Mon 8th July at 12 or 1pm
- DSG is from Mon 5th - Fri 9th August
- Facilitator training Fri 2nd August
- Freeze date 22nd July - Live environments will be deployed from a branch off `master` taken on this date
- Data expected from 22nd to 31 July
- Report writing Mon 12th - Fri 06 Sep
 
## Tasks
- [ ] End to end SHM + DSG deployment test - Tuesday 09 July
- [ ] Decision on whether to include any functional changes to user facing environment
- [ ] Tier 3 developments
   - [ ] Tier 3 managed devices on dedicated network with dedicated IP range 
   - [ ] Package dependency calculation for new requests
   - [ ] Approval process for new requests
   - [ ] Tier 3 R mirrors (Bristol is likely to lean more towards R than Python)
