### ISSUE TITLE
Finishing the policies + processes document

### ISSUE THREAD

**Issue by oforrest** [alan-turing-institute/data-safe-haven#406]
**Tasks that are outstanding:**

- [x] Reviewing redesign of classification flowchart - @jamespjh @martintoreilly 
   - [x] Team signoff (See Issue #405 )
   - [x] Replace in Overleaf 
   - [x] Legal review
   - [x] Make wording changes from legal review - @oforrest 
- [x] Complete sections on 'Management Framework' - @martintoreilly 
- [ ] Complete section 6.2 'Connections to the Secure Environment' - @martintoreilly 
- [ ] . Review Section 10 'Classification Review' - @jamespjh 
- [ ] . Review Section 10 'Classification Review'@martintoreilly 
- [ ] Reorder sections as previously agreed - @oforrest 
- [x] Replace Table 1 and Table 2 (Tier control visualisation) - @oforrest 
- [x] Check wording of data ingress section (8.2), make sure it reflects process rather than software specifics - @martintoreilly @oforrest
- [x] Get signoff from Serena re: new classification flowchart - @oforrest 
- [x] Edit text in Classification section  (8.1, 8.2)to reflect Serena's advice - @oforrest 
- [ ] Review changes to classification section (8.1, 8.2) - @jamespjh @martintoreilly 
- [ ] Review section 8 changes @martintoreilly
