### ISSUE TITLE
Build safe haven software package mirrors for MVP0

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/data-safe-haven#78]
**Note:** A checked box means that the item is either done or being tracked in its own issue and therefore shouldn't block the closure of this issue. We should close this issue when we have reached MVP0 for package mirrors, which is **PyPI** and **CRAN** only.

Our [software ingress policy](https://github.com/alan-turing-institute/data-safe-haven/wiki/SoftwareIngressPolicy) and [analysis environment design](https://github.com/alan-turing-institute/data-safe-haven/wiki/AnalysisEnvironmentDesign) require a full local mirror of the following package repositories:

- [x] Python: pip and conda (implemented in PR #99)
- [x] R: CRAN (implemented in PR #99)
- [x] R Bioconductor (tracked in issue #206)

Package repositories for other languages are not specified, but the environment will support the following languages, so in the longer term we should mirror the standard package repositories / standard libraries for these where they exists. For December I think we should prioritise R and Python unless another language is critical for a particular group. Once we have the DSG safe havens deployed with these repositories, then we can look at adding other languages if we have time.

- [x] **Julia:** Packages are hosted on Github (or potentially other online repos) by their developers, with metadata for registered packages held on the official [Julia Github repo](https://github.com/JuliaLang/METADATA.jl). There is a [project](https://github.com/UnofficialJuliaMirror), that mirrors these repos so we could potentially amend their [MirrorUpdator](https://github.com/UnofficialJuliaMirror/MirrorUpdater.jl) tool to work with a local Git repo rather than Github.com. See issue #204 for this work.
- [x] **Java JVM**: Maven looks like it can be [mirrored](https://maven.apache.org/guides/mini/guide-mirror-settings.html) (tracked in issue #207)
- [x] **.NET Core and mono**: NuGet. Looks like there are [tools](https://github.com/emgarten/NuGet.CatalogReader) to mirror the repository. (tracked in issue #208)
- [ ] C/C++: ???
- [ ] Fortran: ???

- [ ] Q: What about Scala. It's one of the common Spark languages?
@cathiest do we know what language the group that would like Hadoop use?

>For standard packages, the following policy applies:
>
>- For Tier-3 Pip, cran, yum and maven installation will be from local mirror servers with whitelisted software.
>
>- For Tier-2 Pip, cran, yum and maven installation will be from local mirrors with the full set of software mirrored. The local mirror will be one month behind the public repository to ensure a period for a security issue with the public repository to be noticed. Note that this only provides additional confidence for well used packages.
>
>- For Tier-1 and Tier-0, installation will be from the open internet.
