### ISSUE TITLE
Support deallocation and reallocation of Firewall

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/data-safe-haven#783]
#### Description
:scroll: The Azure Firewall cannot be stopped and started from the portal but can be deallocated and allocated using Powershell. When a subscription runs out of credits, the Firewall is deallocated automatically. Therefore we should ensure that the VM is allocated when ensuring SHM Identity VMs are started. To save costs, we should also ensure the Firewall is deallocated when ensuring SHM VMs are stopped.

#### Desired behaviour
:strawberry: When ensuring SHM Identity VMs are stopped or started via the SHM VM Management script, the script also ensures the Azure Firewall is deallocated or allocated respectively.

#### Tasks
:page_facing_up: Include specific tasks in the order they need to be done in.
- [ ] Add `Start-Firewall` and `Stop-Firewall` functions in `Deployments.psm1`
- [ ] Update `Deploy-Firewall` function in `Deployments.psm1` to start Firewall if it is deallocated
- [ ] Call `Start-Firewall` rather than `Get-AzFirewall` in `Setup_SRE_Firewall.ps1`
