### ISSUE TITLE
Update DSVM Ubuntu version to 20.04

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#792]
#### Description
Update the base Ubuntu version for DSVM images to 20.04.

#### Desired behaviour
All new DSVM deployments should be using an image based off 20.04.

#### Notes
- Consider CIS image from alan-turing-institute/data-safe-haven-production#38 
- ~~Wait until alan-turing-institute/data-safe-haven#769 is merged before starting this~~

#### Tasks
- [x] Update image base
- [x] Clarify image naming scheme
- [x] Build new image
