### ISSUE TITLE
Update Python versions

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#794]
#### Description
We have been supporting the same Python versions for a while now. We should update to newer ones. Note that Python 2 is no longer receiving updates so we should be discouraging people from using it.

#### Desired behaviour
DSVM uses newer Python versions.

#### Tasks
- [x] Add Python 3.8 support (with appropriate packages)
- [x] Drop Python 2.7 support (to be discussed)
- [x] Ensure that all hard-coded references to supported versions are made easy-to-change
