### ISSUE TITLE
Attempt to carry out security evaluation checklist and update doc

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#932]
For a given release we want to ensure a to be able to carry out manual test of everything in the [checklist](https://github.com/alan-turing-institute/data-safe-haven/blob/security-checklist-doc-edits/docs/reference/checklists/security-checklist.md) <- this link is to the branch with the doc I'm updating. 

Closing this issue will mean we can the checklist itself is in a state where this is possible.

TODOs:

- [ ] First pass updating docs #982, screenshot results into #977
- [ ] Update the ingress sections, alongside rest of docs #946
- [ ] Final pass on the security checklist, simplifying as much as possible (fewer sub-sections wherever possible)
