### ISSUE TITLE
Decide upon a Git workflow for the repo/project going forward

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#964]
#### :strawberry: Description/desired behaviour

As discussed in the technical meeting on 10th March 2021:

Currently our process is to simply merge feature branches into master, but we have reached a point in the project where it would be valuable to have releases, where we can be certain all the deployment code and documentation has been tested. This will also feed in to #953 as we can begin making release announcements on the slack space which has external collaborators.

@jemrobinson @tomaslaz I think you spoke about this further, so feel free to edit this issue as per your discussion.

#### Suggestion
- Have one branch that *ought to work but hasn't been tested* (`development`?)
- Have one branch that releases are tagged from (`releases`?) that the development branch is merged into whenever we want to make a new release
- Have the releases (tested) branch as the default

#### Todo
- [ ] rename `master` to `development`
- [ ] create a new `main` branch (see #692) which will only contain releases (can be a copy of master up-until the most recent release)
- [ ] future releases will be started by branching off `development` and testing. When ready this branch should be merged into `main` and also back into `development`
- [ ] `main` will be the new default branch

#### :page_facing_up: Tasks
- [x] Choose a workflow, for examples, see here: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
- [x] Define where release announcements are made (on Slack and by email)
- [ ] Decide whether older releases get support or not
