### ISSUE TITLE
Example issue: Carry out security evaluation checklist and provide evidence

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#977]
#### :strawberry: Description/desired behaviour
Carry out security evaluation [checklist](https://github.com/alan-turing-institute/data-safe-haven/blob/security-checklist-doc-edits/docs/reference/checklists/security-checklist.md) (this link is to the branch with the doc I'm updating) on SRE's deployed from latest release `3.2.0` code.

Using SHM: `testa`, T2 SRE: `sandbox` & T3 SRE: `t3test`

Check this when each section verified and **copy screenshots into the issue comments as evidence**:

#### :page_facing_up: Checklist items
1. [x] Multifactor Authentication and Password strength
2. [x] Isolated Network
3. [x] User devices
4. [x] Physical security
5. [x] Copy-and-paste
6. [x] Data ingress
7. [x] Storage volumes and egress
8. [x] Software Ingress
9. [x] Package mirrors
10. [x] Azure Firewalls
11. [x] Non technical security implementation
